use database fuel_prices;

use schema silver;

CREATE OR REPLACE TABLE SILVER.DIM_STATION (
    IDEESS       VARCHAR NOT NULL,
    ROTULO       VARCHAR,
    DIRECCION    VARCHAR,
    MUNICIPIO    VARCHAR,
    PROVINCIA    VARCHAR,
    CCAA         VARCHAR,
    LAT          NUMBER(10,6),
    LON          NUMBER(10,6),

    CONSTRAINT PK_DIM_STATION PRIMARY KEY (IDEESS)
);

CREATE OR REPLACE TABLE SILVER.FCT_PRICE_SNAPSHOT (
    INGESTION_TS  TIMESTAMP_TZ NOT NULL,
    IDEESS        VARCHAR NOT NULL,
    PRODUCT       VARCHAR NOT NULL,
    PRICE_EUR_L   NUMBER(10,3),

    CONSTRAINT PK_FCT_PRICE_SNAPSHOT
        PRIMARY KEY (INGESTION_TS, IDEESS, PRODUCT)
);


select * from fct_price_snapshot where IDEESS = '514' order by product, ingestion_ts;

select * from dim_station where municipio = 'Outes';

select count(distinct ingestion_ts) from fct_price_snapshot;

DESC TABLE SILVER.fct_price_snapshot;

DESC TABLE SILVER.dim_station;

SELECT
    PRODUCT,
    COUNT(*) AS NUM_REGISTROS
FROM SILVER.FCT_PRICE_SNAPSHOT
GROUP BY PRODUCT
ORDER BY PRODUCT;

SELECT
    COUNT(*) AS TOTAL,
    COUNT(DISTINCT INGESTION_TS) AS SNAPSHOTS,
    COUNT(DISTINCT IDEESS) AS ESTACIONES
FROM SILVER.FCT_PRICE_SNAPSHOT;

CREATE TABLE IF NOT EXISTS SILVER.ETL_LOG (
    LOG_ID NUMBER AUTOINCREMENT,
    LOAD_TS TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    INGESTION_TS TIMESTAMP_TZ,
    RAW_COUNT NUMBER,
    SILVER_COUNT NUMBER,
    GOLD_COUNT NUMBER,
    STATUS VARCHAR(20),
    MESSAGE VARCHAR(500)
);