use database fuel_prices;

use schema gold;

---------- Dimensión de estación  ----------------

CREATE OR REPLACE TABLE FUEL_PRICES.GOLD.DIM_STATION (
    STATION_KEY NUMBER(38,0) NOT NULL,
    IDEESS      VARCHAR NOT NULL,
    ROTULO      VARCHAR,
    DIRECCION   VARCHAR,
    MUNICIPIO   VARCHAR,
    PROVINCIA   VARCHAR,
    CCAA        VARCHAR,
    LAT         NUMBER(10,6),
    LON         NUMBER(10,6),

    CONSTRAINT PK_DIM_STATION
        PRIMARY KEY (STATION_KEY)
);


CREATE OR REPLACE TABLE FUEL_PRICES.GOLD.DIM_PRODUCT (
    PRODUCT_KEY NUMBER(38,0) NOT NULL,
    PRODUCT     VARCHAR NOT NULL,

    CONSTRAINT PK_DIM_PRODUCT
        PRIMARY KEY (PRODUCT_KEY)
);


CREATE OR REPLACE TABLE FUEL_PRICES.GOLD.DIM_DATETIME (
    DATETIME_KEY NUMBER(38,0) NOT NULL,
    INGESTION_TS TIMESTAMP_TZ NOT NULL,
    FECHA        DATE,
    HORA         TIME,
    DIA          NUMBER,
    MES          NUMBER,
    ANO          NUMBER,

    CONSTRAINT PK_DIM_DATETIME
        PRIMARY KEY (DATETIME_KEY)
);



CREATE OR REPLACE TABLE FUEL_PRICES.GOLD.FACT_FUEL_PRICE (
    STATION_KEY  NUMBER(38,0) NOT NULL,
    PRODUCT_KEY  NUMBER(38,0) NOT NULL,
    DATETIME_KEY NUMBER(38,0) NOT NULL,
    IDEESS       VARCHAR NOT NULL,
    INGESTION_TS TIMESTAMP_TZ NOT NULL,
    PRICE_EUR_L  NUMBER(10,3),

    -- Clave primaria lógica de la fila de hechos
    CONSTRAINT PK_FACT_FUEL_PRICE
        PRIMARY KEY (
            IDEESS,
            PRODUCT_KEY,
            INGESTION_TS
        ),

    -- FK hacia DIM_STATION
    CONSTRAINT FK_FACT_STATION
        FOREIGN KEY (STATION_KEY)
        REFERENCES FUEL_PRICES.GOLD.DIM_STATION (STATION_KEY),

    -- FK hacia DIM_PRODUCT
    CONSTRAINT FK_FACT_PRODUCT
        FOREIGN KEY (PRODUCT_KEY)
        REFERENCES FUEL_PRICES.GOLD.DIM_PRODUCT (PRODUCT_KEY),

    -- FK hacia DIM_DATETIME
    CONSTRAINT FK_FACT_DATETIME
        FOREIGN KEY (DATETIME_KEY)
        REFERENCES FUEL_PRICES.GOLD.DIM_DATETIME (DATETIME_KEY)
);
FUEL_PRICES.GOLD


------------- COMPROBAMOS TABLAS ------------

SELECT COUNT(*) FROM gold.dim_station;

select count(*) from gold.dim_product;

select count(*) from gold.dim_datetime;

select count(*) from gold.fact_fuel_price;

-------------- COMPROBAMOS GRANULARIDAD --------------

SELECT
    IDEESS,
    PRODUCT_KEY,
    INGESTION_TS,
    COUNT(*) AS NUM_REGISTROS
FROM GOLD.FACT_FUEL_PRICE
GROUP BY
    IDEESS,
    PRODUCT_KEY,
    INGESTION_TS
HAVING COUNT(*) > 1;



