CREATE OR REPLACE TASK FUEL_PRICES.SILVER.TASK_REFRESH_FUEL_DATA
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '3 HOURS'
AS
    CALL FUEL_PRICES.SILVER.REFRESH_FUEL_DATA();

ALTER TASK FUEL_PRICES.SILVER.TASK_REFRESH_FUEL_DATA RESUME;

SHOW TASKS LIKE 'TASK_REFRESH_FUEL_DATA';

EXECUTE TASK FUEL_PRICES.SILVER.TASK_REFRESH_FUEL_DATA;

SELECT
    NAME,
    STATE,
    SCHEDULED_TIME,
    QUERY_START_TIME,
    COMPLETED_TIME,
    ERROR_MESSAGE
FROM TABLE(
    INFORMATION_SCHEMA.TASK_HISTORY(
        TASK_NAME => 'TASK_REFRESH_FUEL_DATA'
    )
)
ORDER BY SCHEDULED_TIME DESC
LIMIT 5;