CREATE DATABASE FUEL_PRICES;

USE DATABASE FUEL_PRICES;

CREATE SCHEMA RAW;

-------------------- BRONZE ------------------

USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW.FUEL_PRICES_JSON (
    INGESTION_ID   VARCHAR,
    INGESTION_TS   TIMESTAMP_TZ,
    RECORD_COUNT   NUMBER,
    PAYLOAD        VARIANT,
    SOURCE_URL     VARCHAR
);

CREATE TABLE RAW.INGESTION_LOG (
    INGESTION_TS TIMESTAMP_TZ,
    STATUS VARCHAR,
    RECORD_COUNT NUMBER,
    ERROR_MESSAGE VARCHAR
);


SELECT
    INGESTION_ID,
    INGESTION_TS,
    RECORD_COUNT,
    ARRAY_SIZE(PAYLOAD:ListaEESSPrecio) AS JSON_RECORD_COUNT,
    SOURCE_URL
FROM RAW.FUEL_PRICES_JSON
ORDER BY INGESTION_TS DESC;

SELECT
    PAYLOAD:ListaEESSPrecio[0]
FROM RAW.FUEL_PRICES_JSON
ORDER BY INGESTION_TS DESC
LIMIT 1;

SELECT
    COUNT(*) AS NUM_CAPTURAS,
    MIN(INGESTION_TS) AS PRIMERA_CAPTURA,
    MAX(INGESTION_TS) AS ULTIMA_CAPTURA
FROM RAW.FUEL_PRICES_JSON;
